import type { Metadata } from "next";
import { Azeret_Mono } from "next/font/google";
import "./globals.css";

const sansSerif = Azeret_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CHENG, KANG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sansSerif.className}>{children}</body>
    </html>
  );
}
